### ISSUE TITLE
the discord API doesnt work anymore

### ISSUE THREAD

**Issue by Emmanuel-DUFOUR** [useapi/discord-cdn-proxy#1]
calls to 
https://discord.com/api/v9/attachments/refresh-urls
return a 400 error

**Comment by useapi** [comment]
I work just fine
![discord_cdn](https://github.com/user-attachments/assets/cefca148-54dc-448d-8bef-b62b9dd50d05)
You can also see it in action at [Discord CDN Proxy](https://useapi.net/docs/articles/discord-cdn-proxy)

**Comment by useapi** [comment]
Service is fully functional
